# Generated by Django 4.1.1 on 2022-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(
                max_length=20, null=True, verbose_name="select_country"
            ),
        ),
    ]
