# Generated by Django 4.1.1 on 2022-09-30 17:47

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, null=True, unique_for_date="publish"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Enter your keywords, enter about 5 keywords",
                    ),
                ),
                ("body", models.TextField(null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.upload_to,
                        verbose_name="Image",
                    ),
                ),
                ("publish", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_category",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-publish"],
            },
        ),
    ]
